#!/bin/bash
set -e -o pipefail


die() { echo "$(basename "$0"):" "$@"; exit 1; }

rpmbuild --version >/dev/null || die "Please 'sudo yum install rpm-build'"

basedir="$(cd $(dirname $0) && pwd -P)"
topdir_macro="%_topdir $basedir"
grep -s -q "^$topdir_macro\$" ~/.rpmmacros || {
    [[ -e ~/.rpmmacros ]] && die "%_topdir in ~/.rpmmacros is wrong; aborting."
    echo "$topdir_macro" > ~/.rpmmacros
}

# Steps below are in (non-strict) order of execution for -ba (build all)
rpmbuild -bs SPECS/ct1.spec     # Build SRPM only
