#!/bin/bash
set -e -o pipefail


die() { echo "$(basename "$0"):" "$@"; exit 1; }

clean=false; [[ _$1 = _-C ]] && { clean=true; shift; }

rpmbuild --version >/dev/null || die "Please 'sudo yum install rpm-build'"

basedir="$(cd $(dirname $0) && pwd -P)"
topdir_macro="%_topdir $basedir"
grep -s -q "^$topdir_macro\$" ~/.rpmmacros || {
    [[ -e ~/.rpmmacros ]] && die "%_topdir in ~/.rpmmacros is wrong; aborting."
    echo "$topdir_macro" > ~/.rpmmacros
}

$clean && rm -rf \
    "$basedir/BUILD" "$basedir/BUILDROOT" "$basedir/RPMS" "$basedir/SRPMS"

build() {
    local buildarg=
    buildcmd="rpmbuild $1 SPECS/$2.spec"
    echo; echo "===== $buildcmd"
    $buildcmd
}

# Steps below are in (non-strict) order of execution for -ba (build all)
build -bs ct1           # Build SRPM only
build -bp ct1           # %prep: unpack sources and apply patches
build -bc ct1           # %build
build -bi ct1           # %install (also does -bi %files list check)
build -bb ct1           # Build binary package and remove work dir in BUILDROOT

echo; echo "===== Package contents:"
rpm2cpio RPMS/x86_64/ct1-0.0-1.x86_64.rpm | cpio -tv
