#!/bin/bash
set -e -o pipefail


die() { echo "$(basename "$0"):" "$@"; exit 1; }

clean=false; [[ _$1 = _-C ]] && { clean=true; shift; }

rpmbuild --version >/dev/null || die "Please 'sudo yum install rpm-build'"

basedir="$(cd $(dirname $0) && pwd -P)"
topdir_macro="%_topdir $basedir"
grep -s -q "^$topdir_macro\$" ~/.rpmmacros || {
    [[ -e ~/.rpmmacros ]] && die "%_topdir in ~/.rpmmacros is wrong; aborting."
    echo "$topdir_macro" > ~/.rpmmacros
}

$clean && rm -rf \
    "$basedir/BUILD" "$basedir/BUILDROOT" "$basedir/RPMS" "$basedir/SRPMS"

# Steps below are in (non-strict) order of execution for -ba (build all)
rpmbuild -bs SPECS/ct1.spec     # Build SRPM only
rpmbuild -bp SPECS/ct1.spec     # %prep: unpack sources and apply patches
